// This file is autogenerated by scripts/build-registry.js
// Do not edit this file directly.
// @ts-nocheck
import * as React from "react";

export const Index: Record<string, any> = {
  "button-as-child": {
    name: "button-as-child",
    description: "button-as-child component",
    type: "registry:block",
    registryDependencies: [],
    files: [{
        path: "registry/default/blocks/button-as-child.tsx",
        type: "registry:block",
        target: "components/blocks/button-as-child.tsx"
      }],
    component: React.lazy(async () => {
      const mod = await import("../registry/default/blocks/button-as-child")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "button-as-child"
      return { default: mod.default || mod[exportName] }
    }),
    meta: {"tags":[]},
  },
  "button-default": {
    name: "button-default",
    description: "button-default component",
    type: "registry:block",
    registryDependencies: [],
    files: [{
        path: "registry/default/blocks/button-default.tsx",
        type: "registry:block",
        target: "components/blocks/button-default.tsx"
      }],
    component: React.lazy(async () => {
      const mod = await import("../registry/default/blocks/button-default")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "button-default"
      return { default: mod.default || mod[exportName] }
    }),
    meta: {"tags":[]},
  },
  "button-demo": {
    name: "button-demo",
    description: "button-demo component",
    type: "registry:block",
    registryDependencies: [],
    files: [{
        path: "registry/default/blocks/button-demo.tsx",
        type: "registry:block",
        target: "components/blocks/button-demo.tsx"
      }],
    component: React.lazy(async () => {
      const mod = await import("../registry/default/blocks/button-demo")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "button-demo"
      return { default: mod.default || mod[exportName] }
    }),
    meta: {"tags":[]},
  },
  "button-destructive": {
    name: "button-destructive",
    description: "button-destructive component",
    type: "registry:block",
    registryDependencies: [],
    files: [{
        path: "registry/default/blocks/button-destructive.tsx",
        type: "registry:block",
        target: "components/blocks/button-destructive.tsx"
      }],
    component: React.lazy(async () => {
      const mod = await import("../registry/default/blocks/button-destructive")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "button-destructive"
      return { default: mod.default || mod[exportName] }
    }),
    meta: {"tags":[]},
  },
  "button-dialog-footer": {
    name: "button-dialog-footer",
    description: "button-dialog-footer component",
    type: "registry:block",
    registryDependencies: [],
    files: [{
        path: "registry/default/blocks/button-dialog-footer.tsx",
        type: "registry:block",
        target: "components/blocks/button-dialog-footer.tsx"
      }],
    component: React.lazy(async () => {
      const mod = await import("../registry/default/blocks/button-dialog-footer")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "button-dialog-footer"
      return { default: mod.default || mod[exportName] }
    }),
    meta: {"tags":[]},
  },
  "button-disabled": {
    name: "button-disabled",
    description: "button-disabled component",
    type: "registry:block",
    registryDependencies: [],
    files: [{
        path: "registry/default/blocks/button-disabled.tsx",
        type: "registry:block",
        target: "components/blocks/button-disabled.tsx"
      }],
    component: React.lazy(async () => {
      const mod = await import("../registry/default/blocks/button-disabled")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "button-disabled"
      return { default: mod.default || mod[exportName] }
    }),
    meta: {"tags":[]},
  },
  "button-double-icon": {
    name: "button-double-icon",
    description: "button-double-icon component",
    type: "registry:block",
    registryDependencies: [],
    files: [{
        path: "registry/default/blocks/button-double-icon.tsx",
        type: "registry:block",
        target: "components/blocks/button-double-icon.tsx"
      }],
    component: React.lazy(async () => {
      const mod = await import("../registry/default/blocks/button-double-icon")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "button-double-icon"
      return { default: mod.default || mod[exportName] }
    }),
    meta: {"tags":[]},
  },
  "button-form-actions": {
    name: "button-form-actions",
    description: "button-form-actions component",
    type: "registry:block",
    registryDependencies: [],
    files: [{
        path: "registry/default/blocks/button-form-actions.tsx",
        type: "registry:block",
        target: "components/blocks/button-form-actions.tsx"
      }],
    component: React.lazy(async () => {
      const mod = await import("../registry/default/blocks/button-form-actions")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "button-form-actions"
      return { default: mod.default || mod[exportName] }
    }),
    meta: {"tags":[]},
  },
  "button-full-width": {
    name: "button-full-width",
    description: "button-full-width component",
    type: "registry:block",
    registryDependencies: [],
    files: [{
        path: "registry/default/blocks/button-full-width.tsx",
        type: "registry:block",
        target: "components/blocks/button-full-width.tsx"
      }],
    component: React.lazy(async () => {
      const mod = await import("../registry/default/blocks/button-full-width")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "button-full-width"
      return { default: mod.default || mod[exportName] }
    }),
    meta: {"tags":[]},
  },
  "button-ghost": {
    name: "button-ghost",
    description: "button-ghost component",
    type: "registry:block",
    registryDependencies: [],
    files: [{
        path: "registry/default/blocks/button-ghost.tsx",
        type: "registry:block",
        target: "components/blocks/button-ghost.tsx"
      }],
    component: React.lazy(async () => {
      const mod = await import("../registry/default/blocks/button-ghost")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "button-ghost"
      return { default: mod.default || mod[exportName] }
    }),
    meta: {"tags":[]},
  },
  "button-groups": {
    name: "button-groups",
    description: "button-groups component",
    type: "registry:block",
    registryDependencies: [],
    files: [{
        path: "registry/default/blocks/button-groups.tsx",
        type: "registry:block",
        target: "components/blocks/button-groups.tsx"
      }],
    component: React.lazy(async () => {
      const mod = await import("../registry/default/blocks/button-groups")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "button-groups"
      return { default: mod.default || mod[exportName] }
    }),
    meta: {"tags":[]},
  },
  "button-icon-left": {
    name: "button-icon-left",
    description: "button-icon-left component",
    type: "registry:block",
    registryDependencies: [],
    files: [{
        path: "registry/default/blocks/button-icon-left.tsx",
        type: "registry:block",
        target: "components/blocks/button-icon-left.tsx"
      }],
    component: React.lazy(async () => {
      const mod = await import("../registry/default/blocks/button-icon-left")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "button-icon-left"
      return { default: mod.default || mod[exportName] }
    }),
    meta: {"tags":[]},
  },
  "button-icon-only": {
    name: "button-icon-only",
    description: "button-icon-only component",
    type: "registry:block",
    registryDependencies: [],
    files: [{
        path: "registry/default/blocks/button-icon-only.tsx",
        type: "registry:block",
        target: "components/blocks/button-icon-only.tsx"
      }],
    component: React.lazy(async () => {
      const mod = await import("../registry/default/blocks/button-icon-only")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "button-icon-only"
      return { default: mod.default || mod[exportName] }
    }),
    meta: {"tags":[]},
  },
  "button-icon-right": {
    name: "button-icon-right",
    description: "button-icon-right component",
    type: "registry:block",
    registryDependencies: [],
    files: [{
        path: "registry/default/blocks/button-icon-right.tsx",
        type: "registry:block",
        target: "components/blocks/button-icon-right.tsx"
      }],
    component: React.lazy(async () => {
      const mod = await import("../registry/default/blocks/button-icon-right")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "button-icon-right"
      return { default: mod.default || mod[exportName] }
    }),
    meta: {"tags":[]},
  },
  "button-link": {
    name: "button-link",
    description: "button-link component",
    type: "registry:block",
    registryDependencies: [],
    files: [{
        path: "registry/default/blocks/button-link.tsx",
        type: "registry:block",
        target: "components/blocks/button-link.tsx"
      }],
    component: React.lazy(async () => {
      const mod = await import("../registry/default/blocks/button-link")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "button-link"
      return { default: mod.default || mod[exportName] }
    }),
    meta: {"tags":[]},
  },
  "button-loading-states": {
    name: "button-loading-states",
    description: "button-loading-states component",
    type: "registry:block",
    registryDependencies: [],
    files: [{
        path: "registry/default/blocks/button-loading-states.tsx",
        type: "registry:block",
        target: "components/blocks/button-loading-states.tsx"
      }],
    component: React.lazy(async () => {
      const mod = await import("../registry/default/blocks/button-loading-states")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "button-loading-states"
      return { default: mod.default || mod[exportName] }
    }),
    meta: {"tags":[]},
  },
  "button-outline": {
    name: "button-outline",
    description: "button-outline component",
    type: "registry:block",
    registryDependencies: [],
    files: [{
        path: "registry/default/blocks/button-outline.tsx",
        type: "registry:block",
        target: "components/blocks/button-outline.tsx"
      }],
    component: React.lazy(async () => {
      const mod = await import("../registry/default/blocks/button-outline")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "button-outline"
      return { default: mod.default || mod[exportName] }
    }),
    meta: {"tags":[]},
  },
  "button-secondary": {
    name: "button-secondary",
    description: "button-secondary component",
    type: "registry:block",
    registryDependencies: [],
    files: [{
        path: "registry/default/blocks/button-secondary.tsx",
        type: "registry:block",
        target: "components/blocks/button-secondary.tsx"
      }],
    component: React.lazy(async () => {
      const mod = await import("../registry/default/blocks/button-secondary")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "button-secondary"
      return { default: mod.default || mod[exportName] }
    }),
    meta: {"tags":[]},
  },
  "button-sizes": {
    name: "button-sizes",
    description: "button-sizes component",
    type: "registry:block",
    registryDependencies: [],
    files: [{
        path: "registry/default/blocks/button-sizes.tsx",
        type: "registry:block",
        target: "components/blocks/button-sizes.tsx"
      }],
    component: React.lazy(async () => {
      const mod = await import("../registry/default/blocks/button-sizes")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "button-sizes"
      return { default: mod.default || mod[exportName] }
    }),
    meta: {"tags":[]},
  },
  "button-social-login": {
    name: "button-social-login",
    description: "button-social-login component",
    type: "registry:block",
    registryDependencies: [],
    files: [{
        path: "registry/default/blocks/button-social-login.tsx",
        type: "registry:block",
        target: "components/blocks/button-social-login.tsx"
      }],
    component: React.lazy(async () => {
      const mod = await import("../registry/default/blocks/button-social-login")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "button-social-login"
      return { default: mod.default || mod[exportName] }
    }),
    meta: {"tags":[]},
  },
  "button-split": {
    name: "button-split",
    description: "button-split component",
    type: "registry:block",
    registryDependencies: [],
    files: [{
        path: "registry/default/blocks/button-split.tsx",
        type: "registry:block",
        target: "components/blocks/button-split.tsx"
      }],
    component: React.lazy(async () => {
      const mod = await import("../registry/default/blocks/button-split")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "button-split"
      return { default: mod.default || mod[exportName] }
    }),
    meta: {"tags":[]},
  },
  "button-toggle": {
    name: "button-toggle",
    description: "button-toggle component",
    type: "registry:block",
    registryDependencies: [],
    files: [{
        path: "registry/default/blocks/button-toggle.tsx",
        type: "registry:block",
        target: "components/blocks/button-toggle.tsx"
      }],
    component: React.lazy(async () => {
      const mod = await import("../registry/default/blocks/button-toggle")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "button-toggle"
      return { default: mod.default || mod[exportName] }
    }),
    meta: {"tags":[]},
  },
  "button-upload": {
    name: "button-upload",
    description: "button-upload component",
    type: "registry:block",
    registryDependencies: [],
    files: [{
        path: "registry/default/blocks/button-upload.tsx",
        type: "registry:block",
        target: "components/blocks/button-upload.tsx"
      }],
    component: React.lazy(async () => {
      const mod = await import("../registry/default/blocks/button-upload")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "button-upload"
      return { default: mod.default || mod[exportName] }
    }),
    meta: {"tags":[]},
  },
  "button-variants": {
    name: "button-variants",
    description: "button-variants component",
    type: "registry:block",
    registryDependencies: [],
    files: [{
        path: "registry/default/blocks/button-variants.tsx",
        type: "registry:block",
        target: "components/blocks/button-variants.tsx"
      }],
    component: React.lazy(async () => {
      const mod = await import("../registry/default/blocks/button-variants")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "button-variants"
      return { default: mod.default || mod[exportName] }
    }),
    meta: {"tags":[]},
  },
  "button-with-avatar": {
    name: "button-with-avatar",
    description: "button-with-avatar component",
    type: "registry:block",
    registryDependencies: [],
    files: [{
        path: "registry/default/blocks/button-with-avatar.tsx",
        type: "registry:block",
        target: "components/blocks/button-with-avatar.tsx"
      }],
    component: React.lazy(async () => {
      const mod = await import("../registry/default/blocks/button-with-avatar")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "button-with-avatar"
      return { default: mod.default || mod[exportName] }
    }),
    meta: {"tags":[]},
  },
  "button-with-badge": {
    name: "button-with-badge",
    description: "button-with-badge component",
    type: "registry:block",
    registryDependencies: [],
    files: [{
        path: "registry/default/blocks/button-with-badge.tsx",
        type: "registry:block",
        target: "components/blocks/button-with-badge.tsx"
      }],
    component: React.lazy(async () => {
      const mod = await import("../registry/default/blocks/button-with-badge")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "button-with-badge"
      return { default: mod.default || mod[exportName] }
    }),
    meta: {"tags":[]},
  },
  "button-with-counter": {
    name: "button-with-counter",
    description: "button-with-counter component",
    type: "registry:block",
    registryDependencies: [],
    files: [{
        path: "registry/default/blocks/button-with-counter.tsx",
        type: "registry:block",
        target: "components/blocks/button-with-counter.tsx"
      }],
    component: React.lazy(async () => {
      const mod = await import("../registry/default/blocks/button-with-counter")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "button-with-counter"
      return { default: mod.default || mod[exportName] }
    }),
    meta: {"tags":[]},
  },
  "button-with-icons": {
    name: "button-with-icons",
    description: "button-with-icons component",
    type: "registry:block",
    registryDependencies: [],
    files: [{
        path: "registry/default/blocks/button-with-icons.tsx",
        type: "registry:block",
        target: "components/blocks/button-with-icons.tsx"
      }],
    component: React.lazy(async () => {
      const mod = await import("../registry/default/blocks/button-with-icons")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "button-with-icons"
      return { default: mod.default || mod[exportName] }
    }),
    meta: {"tags":[]},
  },
  "button-with-keyboard-shortcut": {
    name: "button-with-keyboard-shortcut",
    description: "button-with-keyboard-shortcut component",
    type: "registry:block",
    registryDependencies: [],
    files: [{
        path: "registry/default/blocks/button-with-keyboard-shortcut.tsx",
        type: "registry:block",
        target: "components/blocks/button-with-keyboard-shortcut.tsx"
      }],
    component: React.lazy(async () => {
      const mod = await import("../registry/default/blocks/button-with-keyboard-shortcut")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "button-with-keyboard-shortcut"
      return { default: mod.default || mod[exportName] }
    }),
    meta: {"tags":[]},
  },
};