import type { PatternExampleDefinition } from "@/examples/patterns/example";

export const basicExample: PatternExampleDefinition = {
	html: '<div class="demo-shell card calendar-card">\n  <div class="calendar-header"><button type="button">‹</button><strong>March 2026</strong><button type="button">›</button></div>\n  <div class="calendar-grid"><span class="day">Mon</span><span class="day">Tue</span><span class="day">Wed</span><span class="day">Thu</span><span class="day">Fri</span><span class="day">Sat</span><span class="day">Sun</span><button type="button" class="date">1</button><button type="button" class="date">2</button><button type="button" class="date">3</button><button type="button" class="date">4</button><button type="button" class="date">5</button><button type="button" class="date event">6</button><button type="button" class="date">7</button><button type="button" class="date">8</button><button type="button" class="date">9</button><button type="button" class="date">10</button><button type="button" class="date">11</button><button type="button" class="date">12</button><button type="button" class="date event">13</button><button type="button" class="date">14</button><button type="button" class="date">15</button><button type="button" class="date">16</button><button type="button" class="date">17</button><button type="button" class="date">18</button><button type="button" class="date">19</button><button type="button" class="date event">20</button><button type="button" class="date">21</button><button type="button" class="date">22</button><button type="button" class="date">23</button><button type="button" class="date">24</button><button type="button" class="date">25</button><button type="button" class="date">26</button><button type="button" class="date">27</button><button type="button" class="date">28</button><button type="button" class="date">29</button><button type="button" class="date">30</button><button type="button" class="date">31</button><button type="button" class="date"></button><button type="button" class="date"></button><button type="button" class="date"></button><button type="button" class="date"></button></div>\n</div>',
	css: ".calendar-card { padding: 20px; display: grid; gap: 16px; }\n.calendar-header { display: flex; justify-content: space-between; align-items: center; }\n.calendar-header button { border: 1px solid #cbd5e1; background: white; border-radius: 10px; padding: 8px 12px; }\n.calendar-grid { display: grid; gap: 8px; grid-template-columns: repeat(7, minmax(0, 1fr)); }\n.day { font-size: 12px; color: #64748b; text-align: center; }\n.date { min-height: 52px; border: 1px solid #e2e8f0; border-radius: 12px; background: white; }\n.date.event { background: #dbeafe; border-color: #93c5fd; }",
	js: "",
	height: "460px",
	presentation: "hidden-code",
	variant: "canonical",
};
